version: 2.2.0.{build}

branches:
  except:
    - /.*travis.*/
skip_commits:
  message: /travis/
  files:
    - .travis.yml

environment:
  global:
    EVENT_TESTS_PARALLEL: 20
    EVENT_BUILD_PARALLEL: 10
    MSYS_PATH: C:\msys64
    CYGWIN_PATH: C:\cygwin64
    MINGW_W64_5_3_0: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
    MINGW_W64_6_3_0_I686: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1
    MINGW_W64_6_3_0_X86_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
    MINGW_W64_7_3_0_X86_64: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
    MINGW_W64_8_1_0_X86_64: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0
    MINGW_W64_7_2_0_X86_64: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  matrix:
    - os: Visual Studio 2019
      #    - os: Visual Studio 2015
      #      COMPILER: cygwin
      #    - os: Visual Studio 2017
      #      COMPILER: cygwin
      #    - os: Visual Studio 2019
      #      COMPILER: cygwin
init:
  - 'echo Building libhttpserver %version% for Windows'
  - 'echo System architecture: %PLATFORM%'
  - 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
  - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
  - 'echo Repo build commit is: %APPVEYOR_REPO_COMMIT%'
  - 'echo Cygwin root is: %CYG_ROOT%'
install:
  - |-
      #set msys2="%MSYS_PATH%\msys2_shell.cmd -defterm -no-start"
      #set buildshell="%msys2% -mingw64 -full-path -here"
      #set msys2="%msys2% -msys2"
      set PATH="%MSYS_PATH%\usr\bin;%MINGW_PATH%\bin;%PATH%"
      bash -lc "pacman --sync --noconfirm --disable-download-timeout --needed mingw-w64-x86_64-toolchain"
      bash -lc "pacman -Syu --noconfirm --disable-download-timeout autoconf libtool automake make autoconf-archive pkg-config mingw-w64-x86_64-libsystre mingw-w64-x86_64-doxygen mingw-w64-x86_64-gnutls mingw-w64-x86_64-graphviz mingw-w64-x86_64-curl"
  - curl https://s3.amazonaws.com/libhttpserver/libmicrohttpd_releases/libmicrohttpd-0.9.59.tar.gz -o libmicrohttpd-0.9.59.tar.gz
  - tar -xzf libmicrohttpd-0.9.59.tar.gz
  - cd libmicrohttpd-0.9.59
  - bash -lc "./configure --disable-examples --enable-poll=no"
  - bash -lc "make"
  - bash -lc "make install"
  - cd ..
  - bash -lc "./bootstrap"
  - mkdir build
  - cd build
  - bash -lc "MANIFEST_TOOL='no'; make"
build_script:
  - bash -lc "make check"
  - bash -lc "cat test/test-suite.log"
